import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? AppLocalizations(const Locale('en'));
  }

  static const List<Locale> supportedLocales = [
    Locale('en', ''), // English
    Locale('hi', ''), // Hindi
    Locale('ta', ''), // Tamil
    Locale('te', ''), // Telugu
    Locale('kn', ''), // Kannada
    Locale('gu', ''), // Gujarati
    Locale('mr', ''), // Marathi
  ];

  static const Map<String, String> languageNames = {
    'en': 'English',
    'hi': 'हिंदी (Hindi)',
    'ta': 'தமிழ் (Tamil)',
    'te': 'తెలుగు (Telugu)',
    'kn': 'ಕನ್ನಡ (Kannada)',
    'gu': 'ગુજરાતી (Gujarati)',
    'mr': 'मराठी (Marathi)',
  };

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'KaratCore ERP',
      'dashboard': 'Dashboard',
      'customers': 'Customers',
      'ornaments': 'Inventory & Stock',
      'my_pledged_ornaments': 'My Pledged Ornaments',
      'quality_certificates': 'Quality Certificates',
      'loans': 'Pledges & Loans',
      'my_loans': 'My Active Loans',
      'payments': 'Payments & Receipts',
      'profile': 'My Profile',
      'kyc': 'KYC Verification',
      'settings': 'Store Settings',
      'security': 'Security & 2FA',
      'otp_verification': 'OTP Security Verification',
      'enter_otp': 'Enter 6-Digit OTP Code',
      'send_otp': 'Send OTP Code',
      'resend_otp': 'Resend OTP',
      'two_factor_auth': 'Two-Factor Authentication (2FA)',
      'enable_2fa': 'Enable 2FA Protection',
      'disable_2fa': 'Disable 2FA',
      'authenticator_app': 'Authenticator App (TOTP)',
      'safe_vault_storage': 'Safe Vault Storage',
      'bis_hallmark': 'BIS Hallmark 916 Certified',
      'net_weight': 'Net Gold Weight',
      'gross_weight': 'Gross Weight',
      'purity': 'Gold Purity',
      'valuation': 'Appraised Market Valuation',
      'view_certificate': 'View Quality Certificate',
      'download_pdf': 'Download Certificate PDF',
      'print': 'Print Document',
      'pay_interest': 'Pay Interest',
      'customer_portal': 'Customer Portal',
      'owner_login': 'Owner Login',
      'customer_login': 'Customer OTP Login',
      'mobile_number': 'Mobile Number',
      'verify_and_continue': 'Verify & Continue',
      'language': 'Language',
      'select_language': 'Select App Language',
      'status': 'Status',
      'active': 'Active',
      'closed': 'Closed',
      'vault_secure': 'VAULT SECURE',
    },
    'hi': {
      'app_name': 'कैरेटकोर ईआरपी',
      'dashboard': 'डैशबोर्ड',
      'customers': 'ग्राहक',
      'ornaments': 'इन्वेंटरी और स्टॉक',
      'my_pledged_ornaments': 'मेरे गिरवी गहने',
      'quality_certificates': 'गुणवत्ता प्रमाण पत्र',
      'loans': 'गिरवी और ऋण',
      'my_loans': 'मेरे सक्रिय ऋण',
      'payments': 'भुगतान और रसीदें',
      'profile': 'मेरी प्रोफ़ाइल',
      'kyc': 'केवाईसी सत्यापन',
      'settings': 'स्टोर सेटिंग्स',
      'security': 'सुरक्षा और 2FA',
      'otp_verification': 'ओटीपी सुरक्षा सत्यापन',
      'enter_otp': '6-अंकीय ओटीपी दर्ज करें',
      'send_otp': 'ओटीपी भेजें',
      'resend_otp': 'ओटीपी पुनः भेजें',
      'two_factor_auth': 'टू-फैक्टर प्रमाणीकरण (2FA)',
      'enable_2fa': '2FA सुरक्षा सक्षम करें',
      'disable_2fa': '2FA अक्षम करें',
      'authenticator_app': 'ऑथेंटिकेटर ऐप (TOTP)',
      'safe_vault_storage': 'सुरक्षित वॉल्ट स्टोरेज',
      'bis_hallmark': 'बीआईएस हॉलमार्क 916 प्रमाणित',
      'net_weight': 'शुद्ध सोने का वजन',
      'gross_weight': 'सकल वजन',
      'purity': 'सोने की शुद्धता',
      'valuation': 'मूल्यांकित बाजार मूल्य',
      'view_certificate': 'गुणवत्ता प्रमाणपत्र देखें',
      'download_pdf': 'प्रमाणपत्र पीडीएफ डाउनलोड करें',
      'print': 'दस्तावेज़ प्रिंट करें',
      'pay_interest': 'ब्याज का भुगतान करें',
      'customer_portal': 'ग्राहक पोर्टल',
      'owner_login': 'मालिक लॉगिन',
      'customer_login': 'ग्राहक ओटीपी लॉगिन',
      'mobile_number': 'मोबाइल नंबर',
      'verify_and_continue': 'सत्यापित करें और आगे बढ़ें',
      'language': 'भाषा',
      'select_language': 'ऐप भाषा चुनें',
      'status': 'स्थिति',
      'active': 'सक्रिय',
      'closed': 'बंद',
      'vault_secure': 'वॉल्ट सुरक्षित',
    },
    'ta': {
      'app_name': 'கேரட்கோர் ERP',
      'dashboard': 'டாஷ்போர்டு',
      'customers': 'வாடிக்கையாளர்கள்',
      'ornaments': 'ஆபரணங்கள் & இருப்பு',
      'my_pledged_ornaments': 'எனது அடகு ஆபரணங்கள்',
      'quality_certificates': 'தரச் சான்றிதழ்கள்',
      'loans': 'அடகு & கடன்கள்',
      'my_loans': 'எனது கடன்கள்',
      'payments': 'செலுத்துதல்கள் & ரசீதுகள்',
      'profile': 'என் சுயவிவரம்',
      'kyc': 'KYC சரிபார்ப்பு',
      'settings': 'அமைப்புகள்',
      'security': 'பாதுகாப்பு & 2FA',
      'otp_verification': 'OTP பாதுகாப்பு சரிபார்ப்பு',
      'enter_otp': '6-இலக்க OTP உள்ளிடவும்',
      'send_otp': 'OTP அனுப்பு',
      'resend_otp': 'OTP மீண்டும் அனுப்பு',
      'two_factor_auth': 'இரு காரணி அங்கீகாரம் (2FA)',
      'enable_2fa': '2FA பாதுகாப்பை செயல்படுத்து',
      'disable_2fa': '2FA முடக்கு',
      'authenticator_app': 'அங்கீகார செயலி (TOTP)',
      'safe_vault_storage': 'பாதுகாப்பான பெட்டகம்',
      'bis_hallmark': 'BIS ஹால்மார்க் 916 சான்றளிக்கப்பட்டது',
      'net_weight': 'நிகர தங்கம் எடை',
      'gross_weight': 'மொத்த எடை',
      'purity': 'தங்கத்தின் தூய்மை',
      'valuation': 'மதிப்பீடு செய்யப்பட்ட சந்தை மதிப்பு',
      'view_certificate': 'தரச் சான்றிதழைப் பார்க்கவும்',
      'download_pdf': 'சான்றிதழ் PDF பதிவிறக்கவும்',
      'print': 'அச்சிடுக',
      'pay_interest': 'வட்டி செலுத்தவும்',
      'customer_portal': 'வாடிக்கையாளர் போர்டல்',
      'owner_login': 'உரிமையாளர் உள்நுழைவு',
      'customer_login': 'வாடிக்கையாளர் OTP உள்நுழைவு',
      'mobile_number': 'மொபைல் எண்',
      'verify_and_continue': 'சரிபார்த்து தொடரவும்',
      'language': 'மொழி',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'status': 'நிலை',
      'active': 'செயலில் உள்ளது',
      'closed': 'முடிந்தது',
      'vault_secure': 'பெட்டகம் பாதுகாப்பானது',
    },
    'te': {
      'app_name': 'కారట్‌కోర్ ERP',
      'dashboard': 'డాష్‌బోర్డ్',
      'customers': 'వినియోగదారులు',
      'ornaments': 'ఆభరణాలు & స్టాక్',
      'my_pledged_ornaments': 'నా తాకట్టు ఆభరణాలు',
      'quality_certificates': 'నాణ్యతా ధృవీకరణ పత్రాలు',
      'loans': 'తాకట్టు & రుణాలు',
      'my_loans': 'నా క్రియాశీల రుణాలు',
      'payments': 'చెల్లింపులు & రశీదులు',
      'profile': 'నా ప్రొಫೈಲ್',
      'kyc': 'KYC తనిఖీ',
      'settings': 'స్టోర్ సెట్టింగ్‌లు',
      'security': 'భద్రత & 2FA',
      'otp_verification': 'OTP భద్రతా తనిಖೀ',
      'enter_otp': '6-అంకెల OTP ఎంటర్ చేయండి',
      'send_otp': 'OTP పంపండి',
      'resend_otp': 'ಮళ్లీ OTP పంపండి',
      'two_factor_auth': 'ಟೂ-ಫ್ಯಾಕ್ಟರ್ ప్రామాణీకరణ (2FA)',
      'enable_2fa': '2FA భద్రత ప్రారంభించండి',
      'disable_2fa': '2FA నిలిపివేయండి',
      'authenticator_app': 'ಅಥೆಂಟಿ ಕೇಟರ್ యాప్ (TOTP)',
      'safe_vault_storage': 'ಸುರಕ್ಷಿತ ವಾಲ್ಟ್ ಸ್ಟೋರೇಜ್',
      'bis_hallmark': 'BIS హాల్‌మార్క్ 916 సర్టిఫైడ్',
      'net_weight': 'నికర బంగారు బరువు',
      'gross_weight': 'ಮೊತ್ತಂ ಬರುವು',
      'purity': 'ಬಂಗಾರಂ ಸ್ವಚ್ಛತ',
      'valuation': 'ಮಾರ್ಕೆಟ್ ವಿಲುವ',
      'view_certificate': 'ಸರ್ಟಿಫಿಕೇಟ್ ಚೂಡಂಡಿ',
      'download_pdf': 'PDF ಡೌನ್ ಲೋಡ್ ಚೇಯಂಡಿ',
      'print': 'ಪ್ರಿಂಟ್ ಚೇಯಂಡಿ',
      'pay_interest': 'ವಡ್ಡಿ ಚೆಲ್ಲಿಂಚಂಡಿ',
      'customer_portal': 'ಕಸ್ಟಮರ್ ಪೋರ್ಟಲ್',
      'owner_login': 'ಓನರ್ ಲಾಗಿನ್',
      'customer_login': 'ಕಸ್ಟಮರ್ OTP ಲಾಗಿನ್',
      'mobile_number': 'ಮೊಬೈಲ್ ನಂಬರ್',
      'verify_and_continue': 'ಪರಿಶೀಲಿಂಚಿ ಕೊನಸಾಗಿಂಚಂಡಿ',
      'language': 'ಭಾಷ',
      'select_language': 'ಭಾಷನು ಎಂಚುಕೋಂಡಿ',
      'status': 'ಸ್ಥಿತಿ',
      'active': 'ಯಾಕ್ಟಿವ್',
      'closed': 'ಮುಗಿಸಿಂಧಿ',
      'vault_secure': 'ವಾಲ್ಟ್ ಭದ್ರಂ',
    },
    'kn': {
      'app_name': 'ಕ್ಯಾರಟ್‌ಕೋರ್ ERP',
      'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'customers': 'ಗ್ರಾಹಕರು',
      'ornaments': 'ಆಭರಣಗಳು ಮತ್ತು ದಾಸ್ತಾನು',
      'my_pledged_ornaments': 'ನನ್ನ ಅಡಮಾನ ಆಭರಣಗಳು',
      'quality_certificates': 'ಗುಣಮಟ್ಟ ಪ್ರಮಾಣಪತ್ರಗಳು',
      'loans': 'ಅಡಮಾನ ಮತ್ತು ಸಾಲಗಳು',
      'my_loans': 'ನನ್ನ ಸಕ್ರಿಯ ಸಾಲಗಳು',
      'payments': 'ಪಾವತಿಗಳು ಮತ್ತು ರಸೀದಿಗಳು',
      'profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
      'kyc': 'ಕೆವೈಸಿ ಪರಿಶೀಲನೆ',
      'settings': 'ಅಂಗಡಿ ಸಂಯೋಜನೆಗಳು',
      'security': 'ಸುರಕ್ಷತೆ ಮತ್ತು 2FA',
      'otp_verification': 'OTP ಭದ್ರತಾ ಪರಿಶೀಲನೆ',
      'enter_otp': '6-ಅಂಕಿಯ OTP ನಮೂದಿಸಿ',
      'send_otp': 'OTP ಕಳುಹಿಸಿ',
      'resend_otp': 'OTP ಮರುಕಳುಹಿಸಿ',
      'two_factor_auth': 'ದ್ವಿ-ಅಂಶ ದೃಢೀಕರಣ (2FA)',
      'enable_2fa': '2FA ಸುರಕ್ಷತೆ ಸಕ್ರಿಯಗೊಳಿಸಿ',
      'disable_2fa': '2FA ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ',
      'authenticator_app': 'ಅಥೆಂಟಿಕೇಟರ್ ಆಪ್ (TOTP)',
      'safe_vault_storage': 'ಸುರಕ್ಷಿತ ವಾಲ್ಟ್ ಸಂಗ್ರಹಣೆ',
      'bis_hallmark': 'BIS ಹಾಲ್‌ಮಾರ್ಕ್ 916 ಪ್ರಮಾಣೀಕೃತ',
      'net_weight': 'ನಿವ್ವಳ ಚಿನ್ನದ ತೂಕ',
      'gross_weight': 'ಒಟ್ಟು ತೂಕ',
      'purity': 'ಚಿನ್ನದ ಶುದ್ಧತೆ',
      'valuation': 'ಮೌಲ್ಯಮಾಪನ ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
      'view_certificate': 'ಗುಣಮಟ್ಟ ಪ್ರಮಾಣಪತ್ರ ವೀಕ್ಷಿಸಿ',
      'download_pdf': 'ಪ್ರಮಾಣಪತ್ರ PDF ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
      'print': 'ಮುದ್ರಿಸಿ',
      'pay_interest': 'ಬಡ್ಡಿ ಪಾವತಿಸಿ',
      'customer_portal': 'ಗ್ರಾಹಕ ಪೋರ್ಟಲ್',
      'owner_login': 'ಮಾಲೀಕರ ಲಾಗಿನ್',
      'customer_login': 'ಗ್ರಾಹಕ OTP ಲಾಗಿನ್',
      'mobile_number': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'verify_and_continue': 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ',
      'language': 'ಭಾಷೆ',
      'select_language': 'ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
      'status': 'ಸ್ಥಿತಿ',
      'active': 'ಸಕ್ರಿಯ',
      'closed': 'ಮುಕ್ತಾಯಗೊಂಡಿದೆ',
      'vault_secure': 'ವಾಲ್ಟ್ ಸುರಕ್ಷಿತ',
    },
    'gu': {
      'app_name': 'કેરેટકોર ERP',
      'dashboard': 'ડેશબોર્ડ',
      'customers': 'ગ્રાહકો',
      'ornaments': 'દાગીના અને સ્ટોક',
      'my_pledged_ornaments': 'મારા ગીરવે મૂકેલા દાગીના',
      'quality_certificates': 'ગુણવત્તા પ્રમાણપત્રો',
      'loans': 'ધીરાણ અને લોન',
      'my_loans': 'મારી સક્રિય લોન',
      'payments': 'ચૂકવણી અને રસીદો',
      'profile': 'મારી પ્રોફાઇલ',
      'kyc': 'KYC ચકાસણી',
      'settings': 'સ્ટોર સેટિંગ્સ',
      'security': 'સુરક્ષા અને 2FA',
      'otp_verification': 'OTP સુરક્ષા ચકાસણી',
      'enter_otp': '6-આંકડાનો OTP દાખલ કરો',
      'send_otp': 'OTP મોકલો',
      'resend_otp': 'ફરીથી OTP મોકલો',
      'two_factor_auth': 'ટુ-ફેક્ટર ઓથેન્ટિકેશન (2FA)',
      'enable_2fa': '2FA સુરક્ષા સક્ષમ કરો',
      'disable_2fa': '2FA અક્ષમ કરો',
      'authenticator_app': 'ઓથેન્ટિકેટર એપ (TOTP)',
      'safe_vault_storage': 'સુરક્ષિત તિજોરી',
      'bis_hallmark': 'BIS હોલમાર્ક 916 પ્રમાણિત',
      'net_weight': 'શુદ્ધ સોનાનું વજન',
      'gross_weight': 'કુલ વજન',
      'purity': 'સોનાની શુદ્ધતા',
      'valuation': 'બજાર મૂલ્યાંકન',
      'view_certificate': 'પ્રમાણપત્ર જુઓ',
      'download_pdf': 'PDF ડાઉનલોડ કરો',
      'print': 'પ્રિન્ટ કરો',
      'pay_interest': 'વ્યાજ ચૂકવો',
      'customer_portal': 'ગ્રાહક પોર્ટલ',
      'owner_login': 'ઓનર લોગિન',
      'customer_login': 'ગ્રાહક OTP લોગિન',
      'mobile_number': 'મોબાઈલ નંબર',
      'verify_and_continue': 'ચકાસો અને આગળ વધો',
      'language': 'ભાષા',
      'select_language': 'એપ ભાષા પસંદ કરો',
      'status': 'સ્થિતિ',
      'active': 'સક્રિય',
      'closed': 'બંધ',
      'vault_secure': 'તિજોરી સુરક્ષિત',
    },
    'mr': {
      'app_name': 'कॅरेटकोर ERP',
      'dashboard': 'डॅशबोर्ड',
      'customers': 'ग्राहक',
      'ornaments': 'दागिने आणि साठा',
      'my_pledged_ornaments': 'माझे गहाण ठेवलेले दागिने',
      'quality_certificates': 'गुणवत्ता प्रमाणपत्रे',
      'loans': 'गहाण आणि कर्जे',
      'my_loans': 'माझी सक्रिय कर्जे',
      'payments': 'पेमेंट्स आणि पावत्या',
      'profile': 'माझी प्रोफाइल',
      'kyc': 'केवायसी पडताळणी',
      'settings': 'स्टोअर सेटिंग्ज',
      'security': 'सुरक्षा आणि 2FA',
      'otp_verification': 'OTP सुरक्षा पडताळणी',
      'enter_otp': '6-अंकी OTP प्रविष्ट करा',
      'send_otp': 'OTP पाठवा',
      'resend_otp': 'पुन्हा OTP पाठवा',
      'two_factor_auth': 'टू-फॅक्टर ऑथेंटिकेशन (2FA)',
      'enable_2fa': '2FA सुरक्षा सक्षम करा',
      'disable_2fa': '2FA अक्षम करा',
      'authenticator_app': 'ऑथेंटिकेटर अ‍ॅप (TOTP)',
      'safe_vault_storage': 'सुरक्षित व्हॉल्ट स्टोरेज',
      'bis_hallmark': 'BIS हॉलमार्क 916 प्रमाणित',
      'net_weight': 'शुद्ध सोन्याचे वजन',
      'gross_weight': 'एकूण वजन',
      'purity': 'सोन्याची शुद्धता',
      'valuation': 'मूल्यांकन बाजार किंमत',
      'view_certificate': 'प्रमाणपत्र पहा',
      'download_pdf': 'प्रमाणपत्र PDF डाउनलोड करा',
      'print': 'प्रिंट करा',
      'pay_interest': 'व्याज भरा',
      'customer_portal': 'ग्राहक पोर्टल',
      'owner_login': 'मालक लॉगिन',
      'customer_login': 'ग्राहक OTP लॉगिन',
      'mobile_number': 'मोबाईल नंबर',
      'verify_and_continue': 'पडताळणी करा आणि पुढे जा',
      'language': 'भाषा',
      'select_language': 'अ‍ॅप भाषा निवડા',
      'status': 'स्थिती',
      'active': 'सक्रिय',
      'closed': 'बंद',
      'vault_secure': 'व्हॉल्ट सुरक्षित',
    },
  };

  String translate(String key) {
    final languageCode = locale.languageCode;
    return _localizedValues[languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'hi', 'ta', 'te', 'kn', 'gu', 'mr'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

extension LocalizationContextExtension on BuildContext {
  String tr(String key) {
    return AppLocalizations.of(this).translate(key);
  }
}
