import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? AppLocalizations(const Locale('en'));
  }

  static const List<Locale> supportedLocales = [
    Locale('en', ''), // English
    Locale('hi', ''), // Hindi
    Locale('ta', ''), // Tamil
    Locale('te', ''), // Telugu
    Locale('kn', ''), // Kannada
    Locale('gu', ''), // Gujarati
    Locale('mr', ''), // Marathi
  ];

  static const Map<String, String> languageNames = {
    'en': 'English',
    'hi': 'हिंदी (Hindi)',
    'ta': 'தமிழ் (Tamil)',
    'te': 'తెలుగు (Telugu)',
    'kn': 'ಕನ್ನಡ (Kannada)',
    'gu': 'ગુજરાતી (Gujarati)',
    'mr': 'मराठी (Marathi)',
  };

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'KaratCore ERP',
      'dashboard': 'Dashboard',
      'customers': 'Customers',
      'ornaments': 'Inventory & Stock',
      'my_pledged_ornaments': 'My Pledged Ornaments',
      'quality_certificates': 'Quality Certificates',
      'loans': 'Pledges & Loans',
      'my_loans': 'My Active Loans',
      'payments': 'Payments & Receipts',
      'profile': 'My Profile',
      'kyc': 'KYC Verification',
      'settings': 'Store Settings',
      'security': 'Security & 2FA',
      'otp_verification': 'OTP Security Verification',
      'enter_otp': 'Enter 6-Digit OTP Code',
      'send_otp': 'Send OTP Code',
      'resend_otp': 'Resend OTP',
      'two_factor_auth': 'Two-Factor Authentication (2FA)',
      'enable_2fa': 'Enable 2FA Protection',
      'disable_2fa': 'Disable 2FA',
      'authenticator_app': 'Authenticator App (TOTP)',
      'safe_vault_storage': 'Safe Vault Storage',
      'bis_hallmark': 'BIS Hallmark 916 Certified',
      'net_weight': 'Net Gold Weight',
      'gross_weight': 'Gross Weight',
      'purity': 'Gold Purity',
      'valuation': 'Appraised Market Valuation',
      'view_certificate': 'View Quality Certificate',
      'download_pdf': 'Download Certificate PDF',
      'print': 'Print Document',
      'pay_interest': 'Pay Interest',
      'customer_portal': 'Customer Portal',
      'owner_login': 'Owner Login',
      'customer_login': 'Customer OTP Login',
      'mobile_number': 'Mobile Number',
      'verify_and_continue': 'Verify & Continue',
      'language': 'Language',
      'select_language': 'Select App Language',
      'status': 'Status',
      'active': 'Active',
      'closed': 'Closed',
      'vault_secure': 'VAULT SECURE',
      'core_operations': 'Core Operations',
      'jewellery_and_assets': 'Jewellery & Assets',
      'finance_and_analytics': 'Finance & Analytics',
      'security_and_audit': 'Security & Audit',
      'store_administration': 'Store Administration',
      'accounting_ledger': 'Accounting Ledger',
      'reports_and_analytics': 'Reports & Analytics',
      'audit_log': 'Audit Log',
      'security_activity': 'Security Activity',
      'notifications': 'Notifications',
      'owner_profile': 'Owner Profile',
      'store_settings': 'Store Settings',
      'help_and_docs': 'Help & Docs',
      'kyc_verification': 'KYC Verification',
      'inventory_and_stock': 'Inventory & Stock',
      'pledges_and_loans': 'Pledges & Loans',
      'welcome_back': 'Welcome Back',
      'active_loans': 'Active Loans',
      'total_due_amount': 'Total Due Amount',
      'search_placeholder': 'Search customers, loans...',
      'select_branch': 'Select Branch',
      'view_all': 'View All',
      'language_and_regional': 'Language & Regional',
      'select_app_language_desc': 'Choose your preferred language for KaratCore ERP',
      // Loans & Reports In-Page Strings
      'new_loan_and_pledge': 'New Loan & Pledge',
      'loan_reports': 'Loan Reports',
      'outstanding_principal': 'Outstanding Principal',
      'interest_accrued_due': 'Interest Accrued Due',
      'total_collateral_value': 'Total Collateral Value',
      'loan_portfolio_analytics': 'Loan Portfolio & Collateral Analytics',
      'collateral_distribution': 'Collateral Distribution',
      'gold_collateral_loans': 'Gold Collateral Loans',
      'silver_collateral_loans': 'Silver Collateral Loans',
      'loan_health_performance': 'Loan Health Performance',
      'current_on_time_loans': 'Current On-Time Loans',
      'overdue_interest_accounts': 'Overdue Interest Accounts',
      'search_loans_placeholder': 'Search Loans by Loan ID, Customer Name, Mobile...',
      'filters': 'Filters',
      'date_disbursed_newest': 'Date Disbursed (Newest)',
      'enterprise_module': 'ENTERPRISE MODULE',
      'pledge_and_loans_desc': 'Secured precious-metal lending, customer pledges, interest accruals, repayments, and settlements.',
      'reports_and_bi_center': 'Reports & Business Intelligence Center',
      'reports_bi_desc': 'Executive dashboards, operational analytics, risk indicators & exportable financial statements',
      'report_date_filter': 'Report Date Filter',
      'comparison_mode': 'Comparison Mode',
      'no_comparison': 'No Comparison',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'last_month': 'Last Month',
      'this_quarter': 'This Quarter',
      'this_year': 'This Year',
      'financial_year': 'Financial Year',
      'custom_range': 'Custom Range',
      'attention_required': 'Attention Required — Action Panel',
      'attention_required_desc': 'Rule-based operational indicators requiring owner/manager action',
      'executive_kpi_metrics': 'Executive KPI Summary Metrics',
      'revenue': 'Revenue',
      'expenses': 'Expenses',
      'net_profit': 'Net Profit',
      'loan_outstanding': 'Loan Outstanding',
      'interest_income': 'Interest Income',
      'inventory_value': 'Inventory Value',
      'pledged_inventory': 'Pledged Inventory',
      'customer_count': 'Customer Count',
      'overdue_loans': 'Overdue Loans',
      'cash_balance': 'Cash Balance',
      'overdue_gold_loans': 'Overdue Gold Loans',
      'pending_kyc_records': 'Pending KYC Records',
      'loans_awaiting_approval': 'Loans Awaiting Approval',
      'ornaments_requiring_attention': 'Ornaments Requiring Attention',
      'overdue_receivables': 'Overdue Receivables',
      'high_risk_customers': 'High-Risk Customer Records',
      'bank_balance': 'Bank Balance',
      'saved_pinned_reports': 'Saved & Pinned Report Views',
      'recent_reports': 'Recent Reports & Favorites',
      'dedicated_reports_directory': 'Dedicated Report Modules Directory',
      'reset_filters': 'Reset Filters',
      'previous_period': 'Previous Period',
      'same_period_last_year': 'Same Period Last Year',
    },
    'hi': {
      'app_name': 'कैरेटकोर ईआरपी',
      'dashboard': 'डैशबोर्ड',
      'customers': 'ग्राहक',
      'ornaments': 'इन्वेंटरी और स्टॉक',
      'my_pledged_ornaments': 'मेरे गिरवी गहने',
      'quality_certificates': 'गुणवत्ता प्रमाण पत्र',
      'loans': 'गिरवी और ऋण',
      'my_loans': 'मेरे सक्रिय ऋण',
      'payments': 'भुगतान और रसीदें',
      'profile': 'मेरी प्रोफ़ाइल',
      'kyc': 'केवाईसी सत्यापन',
      'settings': 'स्टोर सेटिंग्स',
      'security': 'सुरक्षा और 2FA',
      'otp_verification': 'ओटीपी सुरक्षा सत्यापन',
      'enter_otp': '6-अंकीय ओटीपी दर्ज करें',
      'send_otp': 'ओटीपी भेजें',
      'resend_otp': 'ओटीपी पुनः भेजें',
      'two_factor_auth': 'टू-फैक्टर प्रमाणीकरण (2FA)',
      'enable_2fa': '2FA सुरक्षा सक्षम करें',
      'disable_2fa': '2FA अक्षम करें',
      'authenticator_app': 'ऑथेंटिकेटर ऐप (TOTP)',
      'safe_vault_storage': 'सुरक्षित वॉल्ट स्टोरेज',
      'bis_hallmark': 'बीआईएस हॉलमार्क 916 प्रमाणित',
      'net_weight': 'शुद्ध सोने का वजन',
      'gross_weight': 'सकल वजन',
      'purity': 'सोने की शुद्धता',
      'valuation': 'मूल्यांकित बाजार मूल्य',
      'view_certificate': 'गुणवत्ता प्रमाणपत्र देखें',
      'download_pdf': 'प्रमाणपत्र पीडीएफ डाउनलोड करें',
      'print': 'दस्तावेज़ प्रिंट करें',
      'pay_interest': 'ब्याज का भुगतान करें',
      'customer_portal': 'ग्राहक पोर्टल',
      'owner_login': 'मालिक लॉगिन',
      'customer_login': 'ग्राहक ओटीपी लॉगिन',
      'mobile_number': 'मोबाइल नंबर',
      'verify_and_continue': 'सत्यापित करें और आगे बढ़ें',
      'language': 'भाषा',
      'select_language': 'ऐप भाषा चुनें',
      'status': 'स्थिति',
      'active': 'सक्रिय',
      'closed': 'बंद',
      'vault_secure': 'वॉल्ट सुरक्षित',
      'core_operations': 'मुख्य संचालन',
      'jewellery_and_assets': 'आभूषण और संपत्तियां',
      'finance_and_analytics': 'वित्त और विश्लेषण',
      'security_and_audit': 'सुरक्षा और ऑडिट',
      'store_administration': 'स्टोर प्रशासन',
      'accounting_ledger': 'लेखा बही (खाताबही)',
      'reports_and_analytics': 'रिपोर्ट और विश्लेषण',
      'audit_log': 'ऑडिट लॉग',
      'security_activity': 'सुरक्षा गतिविधि',
      'notifications': 'सूचनाएं और अलर्ट',
      'owner_profile': 'मालिक प्रोफ़ाइल',
      'store_settings': 'स्टोर सेटिंग्स',
      'help_and_docs': 'सहायता और दस्तावेज़',
      'kyc_verification': 'केवाईसी सत्यापन',
      'inventory_and_stock': 'इन्वेंटरी और स्टॉक',
      'pledges_and_loans': 'गिरवी और ऋण',
      'welcome_back': 'वापसी पर स्वागत है',
      'active_loans': 'सक्रिय ऋण',
      'total_due_amount': 'कुल देय राशि',
      'search_placeholder': 'ग्राहक, ऋण खोजें...',
      'select_branch': 'शाखा चुनें',
      'view_all': 'सभी देखें',
      'language_and_regional': 'भाषा और क्षेत्रीय प्राथमिकताएं',
      'select_app_language_desc': 'कैरेटकोर ईआरपी सिस्टम के लिए अपनी पसंदीदा भाषा चुनें',
      // Loans & Reports In-Page Strings
      'new_loan_and_pledge': 'नया ऋण और गिरवी',
      'loan_reports': 'ऋण रिपोर्ट',
      'outstanding_principal': 'बकाया मूलधन',
      'interest_accrued_due': 'अर्जित ब्याज देय',
      'total_collateral_value': 'कुल संपार्श्विक मूल्य',
      'loan_portfolio_analytics': 'ऋण पोर्टफोलियो और संपार्श्विक विश्लेषण',
      'collateral_distribution': 'संपार्श्विक वितरण',
      'gold_collateral_loans': 'स्वर्ण संपार्श्विक ऋण',
      'silver_collateral_loans': 'रजत संपार्श्विक ऋण',
      'loan_health_performance': 'ऋण स्वास्थ्य प्रदर्शन',
      'current_on_time_loans': 'समय पर सक्रिय ऋण',
      'overdue_interest_accounts': 'अतिदेय ब्याज खाते',
      'search_loans_placeholder': 'ऋण आईडी, ग्राहक नाम, मोबाइल द्वारा खोजें...',
      'filters': 'फ़िल्टर',
      'date_disbursed_newest': 'संवितरण तिथि (नवीनतम)',
      'enterprise_module': 'एंटरप्राइज मॉड्यूल',
      'pledge_and_loans_desc': 'सुरक्षित कीमती-धातु ऋण, ग्राहक गिरवी, ब्याज संचय, पुनर्भुगतान और निपटान।',
      'reports_and_bi_center': 'रिपोर्ट और बिजनेस इंटेलिजेंस केंद्र',
      'reports_bi_desc': 'कार्यकारी डैशबोर्ड, परिचालन विश्लेषण, जोखिम संकेतक और वित्तीय विवरण',
      'report_date_filter': 'रिपोर्ट तिथि फ़िल्टर',
      'comparison_mode': 'तुलना मोड',
      'no_comparison': 'कोई तुलना नहीं',
      'today': 'आज',
      'yesterday': 'कल',
      'this_week': 'इस सप्ताह',
      'this_month': 'इस महीने',
      'last_month': 'पिछले महीने',
      'this_quarter': 'इस तिमाही',
      'this_year': 'इस वर्ष',
      'financial_year': 'वित्तीय वर्ष',
      'custom_range': 'कस्टम रेंज',
      'attention_required': 'ध्यान देने योग्य — कार्य पैनल',
      'attention_required_desc': 'मालिक/प्रबंधक कार्रवाई की आवश्यकता वाले परिचालन संकेतक',
      'executive_kpi_metrics': 'कार्यकारी केपीआई सारांश',
      'revenue': 'राजस्व',
      'expenses': 'खर्च',
      'net_profit': 'शुद्ध लाभ',
      'loan_outstanding': 'बकाया ऋण',
      'interest_income': 'ब्याज आय',
      'inventory_value': 'इन्वेंटरी मूल्य',
      'pledged_inventory': 'गिरवी इन्वेंटरी',
      'customer_count': 'ग्राहक संख्या',
      'overdue_loans': 'अतिदेय ऋण',
      'cash_balance': 'नकद शेष',
      'overdue_gold_loans': 'अतिदेय स्वर्ण ऋण',
      'pending_kyc_records': 'लंबित केवाईसी रिकॉर्ड',
      'loans_awaiting_approval': 'स्वीकृति की प्रतीक्षा में ऋण',
      'ornaments_requiring_attention': 'ध्यान देने योग्य आभूषण',
      'overdue_receivables': 'अतिदेय प्राप्य राशि',
      'high_risk_customers': 'उच्च जोखिम वाले ग्राहक रिकॉर्ड',
      'bank_balance': 'बैंक शेष',
      'saved_pinned_reports': 'सहेजे गए और पिन किए गए रिपोर्ट दृश्य',
      'recent_reports': 'हालिया रिपोर्ट और पसंदीदा',
      'dedicated_reports_directory': 'समर्पित रिपोर्ट मॉड्यूल निर्देशिका',
      'reset_filters': 'फ़िल्टर रीसेट करें',
      'previous_period': 'पिछली अवधि',
      'same_period_last_year': 'पिछले साल की समान अवधि',
    },
    'ta': {
      'app_name': 'கேரட்கோர் ERP',
      'dashboard': 'டாஷ்போர்டு',
      'customers': 'வாடிக்கையாளர்கள்',
      'ornaments': 'ஆபரணங்கள் & இருப்பு',
      'my_pledged_ornaments': 'எனது அடகு ஆபரணங்கள்',
      'quality_certificates': 'தரச் சான்றிதழ்கள்',
      'loans': 'அடகு & கடன்கள்',
      'my_loans': 'எனது கடன்கள்',
      'payments': 'செலுத்துதல்கள் & ரசீதுகள்',
      'profile': 'என் சுயவிவரம்',
      'kyc': 'KYC சரிபார்ப்பு',
      'settings': 'அமைப்புகள்',
      'security': 'பாதுகாப்பு & 2FA',
      'otp_verification': 'OTP பாதுகாப்பு சரிபார்ப்பு',
      'enter_otp': '6-இலக்க OTP உள்ளிடவும்',
      'send_otp': 'OTP அனுப்பு',
      'resend_otp': 'OTP மீண்டும் அனுப்பு',
      'two_factor_auth': 'இரு காரணி அங்கீகாரம் (2FA)',
      'enable_2fa': '2FA பாதுகாப்பை செயல்படுத்து',
      'disable_2fa': '2FA முடக்கு',
      'authenticator_app': 'அங்கீகார செயலி (TOTP)',
      'safe_vault_storage': 'பாதுகாப்பான பெட்டகம்',
      'bis_hallmark': 'BIS ஹால்மார்க் 916 சான்றளிக்கப்பட்டது',
      'net_weight': 'நிகர தங்கம் எடை',
      'gross_weight': 'மொத்த எடை',
      'purity': 'தங்கத்தின் தூய்மை',
      'valuation': 'மதிப்பீடு செய்யப்பட்ட சந்தை மதிப்பு',
      'view_certificate': 'தரச் சான்றிதழைப் பார்க்கவும்',
      'download_pdf': 'சான்றிதழ் PDF பதிவிறக்கவும்',
      'print': 'அச்சிடுக',
      'pay_interest': 'வட்டி செலுத்தவும்',
      'customer_portal': 'வாடிக்கையாளர் போர்டல்',
      'owner_login': 'உரிமையாளர் உள்நுழைவு',
      'customer_login': 'வாடிக்கையாளர் OTP உள்நுழைவு',
      'mobile_number': 'மொபைல் எண்',
      'verify_and_continue': 'சரிபார்த்து தொடரவும்',
      'language': 'மொழி',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'status': 'நிலை',
      'active': 'செயலில் உள்ளது',
      'closed': 'முடிந்தது',
      'vault_secure': 'பெட்டகம் பாதுகாப்பானது',
      'core_operations': 'முதன்மை செயல்பாடுகள்',
      'jewellery_and_assets': 'நகைகள் & சொத்துக்கள்',
      'finance_and_analytics': 'நிதி & பகுப்பாய்வு',
      'security_and_audit': 'பாதுகாப்பு & தணிக்கை',
      'store_administration': 'கடை நிர்வாகம்',
      'accounting_ledger': 'கணக்கு பேரேடு',
      'reports_and_analytics': 'அறிக்கைகள் & பகுப்பாய்வு',
      'audit_log': 'தணிக்கை பதிவு',
      'security_activity': 'பாதுகாப்பு செயல்பாடு',
      'notifications': 'அறிவிப்புகள்',
      'owner_profile': 'உரிமையாளர் சுயவிவரம்',
      'store_settings': 'கடை அமைப்புகள்',
      'help_and_docs': 'உதவி & ஆவணங்கள்',
      'kyc_verification': 'KYC சரிபார்ப்பு',
      'inventory_and_stock': 'ஆபரணங்கள் & இருப்பு',
      'pledges_and_loans': 'அடகு & கடன்கள்',
      'welcome_back': 'மீண்டும் வருக',
      'active_loans': 'செயலில் உள்ள கடன்கள்',
      'total_due_amount': 'மொத்த நிலுவைத் தொகை',
      'search_placeholder': 'வாடிக்கையாளர், கடன்கள் தேடவும்...',
      'select_branch': 'கிளையைத் தேர்ந்தெடுக்கவும்',
      'view_all': 'அனைத்தையும் காண்க',
      'language_and_regional': 'மொழி மற்றும் பிராந்திய விருப்பங்கள்',
      'select_app_language_desc': 'காரட்கோர் ERP பயன்பாட்டிற்கு உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
      // Loans & Reports In-Page Strings
      'new_loan_and_pledge': 'புதிய கடன் & அடகு',
      'loan_reports': 'கடன் அறிக்கைகள்',
      'outstanding_principal': 'நிலுவை முதன்மை',
      'interest_accrued_due': 'சேர்ந்த வட்டி நிலுவை',
      'total_collateral_value': 'மொத்த பிணைய மதிப்பு',
      'loan_portfolio_analytics': 'கடன் போர்ட்ஃபோலியோ & பிணைய பகுப்பாய்வு',
      'collateral_distribution': 'பிணைய விநியோகம்',
      'gold_collateral_loans': 'தங்க பிணைய கடன்கள்',
      'silver_collateral_loans': 'வெள்ளி பிணைய கடன்கள்',
      'loan_health_performance': 'கடன் செயல்திறன்',
      'current_on_time_loans': 'நேரத்திற்கு செலுத்தப்படும் கடன்கள்',
      'overdue_interest_accounts': 'காலாவதியான வட்டி கணக்குகள்',
      'search_loans_placeholder': 'கடன் ஐடி, வாடிக்கையாளர் பெயர் மூலம் தேடவும்...',
      'filters': 'வடிகட்டிகள்',
      'date_disbursed_newest': 'வழங்கப்பட்ட தேதி (புதியது)',
      'enterprise_module': 'நிறுவன தொகுதி',
      'pledge_and_loans_desc': 'பாதுகாப்பான உலோகக் கடன்கள், அடகு வைப்புகள், வட்டி வசூலிப்பு மற்றும் தீர்வுகள்.',
      'reports_and_bi_center': 'அறிக்கைகள் & வணிக நுண்ணறிவு மையம்',
      'reports_bi_desc': 'நிர்வாக டாஷ்போர்டுகள், செயல்பாட்டு பகுப்பாய்வு மற்றும் நிதி அறிக்கைகள்',
      'report_date_filter': 'அறிக்கை தேதி வடிகட்டி',
      'comparison_mode': 'ஒப்பீடு முறை',
      'no_comparison': 'ஒப்பீடு இல்லை',
      'today': 'இன்று',
      'yesterday': 'நேற்று',
      'this_week': 'இந்த வாரம்',
      'this_month': 'இந்த மாதம்',
      'last_month': 'கடந்த மாதம்',
      'this_quarter': 'இந்த காலாண்டு',
      'this_year': 'இந்த ஆண்டு',
      'financial_year': 'நிதியாண்டு',
      'custom_range': 'விருப்ப வரம்பு',
      'attention_required': 'கவனம் தேவை — செயல் குழு',
      'attention_required_desc': 'உரிமையாளர் நடவடிக்கை தேவைப்படும் செயல்பாட்டு குறிகாட்டிகள்',
      'executive_kpi_metrics': 'நிர்வாக KPI சுருக்கம்',
      'revenue': 'வருவாய்',
      'expenses': 'செலவுகள்',
      'net_profit': 'நிகர லாபம்',
      'loan_outstanding': 'கடன் நிலுவை',
      'interest_income': 'வட்டி வருமானம்',
      'inventory_value': 'இருப்பு மதிப்பு',
      'pledged_inventory': 'அடகு வைக்கப்பட்ட இருப்பு',
      'customer_count': 'வாடிக்கையாளர் எண்ணிக்கை',
      'overdue_loans': 'காலாவதியான கடன்கள்',
      'cash_balance': 'ரொக்க இருப்பு',
      'overdue_gold_loans': 'காலாவதியான தங்கக் கடன்கள்',
      'pending_kyc_records': 'நிலுவையில் உள்ள KYC பதிவுகள்',
      'loans_awaiting_approval': 'ஒப்புதலுக்காக காத்திருக்கும் கடன்கள்',
      'ornaments_requiring_attention': 'கவனம் தேவைப்படும் நகைகள்',
      'overdue_receivables': 'தாமதமான நிலுவைத் தொகைகள்',
      'high_risk_customers': 'அதிக ஆபத்துள்ள வாடிக்கையாளர்கள்',
      'bank_balance': 'வங்கி இருப்பு',
      'saved_pinned_reports': 'சேமிக்கப்பட்ட மற்றும் பின் செய்யப்பட்ட அறிக்கைகள்',
      'recent_reports': 'சமீபத்திய அறிக்கைகள் மற்றும் விருப்பமானவை',
      'dedicated_reports_directory': 'பிரத்யேக அறிக்கை தொகுதிகள் அடைவு',
      'reset_filters': 'வடிகட்டிகளை மீட்டமை',
      'previous_period': 'முந்தைய காலம்',
      'same_period_last_year': 'கடந்த ஆண்டின் இதே காலம்',
    },
    'te': {
      'app_name': 'కారట్‌కోర్ ERP',
      'dashboard': 'డాష్‌బోర్డ్',
      'customers': 'వినియోగదారులు',
      'ornaments': 'ఆభరణాలు & స్టాక్',
      'my_pledged_ornaments': 'నా తాకట్టు ఆభరణాలు',
      'quality_certificates': 'నాణ్యతా ధృవీకరణ పత్రాలు',
      'loans': 'తాకట్టు & రుణాలు',
      'my_loans': 'నా క్రియాశీల రుణాలు',
      'payments': 'చెల్లింపులు & రశీదులు',
      'profile': 'నా ప్రొఫైల్',
      'kyc': 'KYC తనిఖీ',
      'settings': 'స్టోర్ సెట్టింగ్‌లు',
      'security': 'భద్రత & 2FA',
      'otp_verification': 'OTP భద్రతా తనిఖీ',
      'enter_otp': '6-అంకెల OTP ఎంటర్ చేయండి',
      'send_otp': 'OTP పంపండి',
      'resend_otp': 'మళ్లీ OTP పంపండి',
      'two_factor_auth': 'టూ-ఫ్యాక్టర్ ప్రామాణీకరణ (2FA)',
      'enable_2fa': '2FA భద్రత ప్రారంభించండి',
      'disable_2fa': '2FA నిలిపివేయండి',
      'authenticator_app': 'ఆథెంటికేటర్ యాప్ (TOTP)',
      'safe_vault_storage': 'సురక్షిత వాల్ట్ నిల్వ',
      'bis_hallmark': 'BIS హాల్‌మార్క్ 916 సర్టిఫైడ్',
      'net_weight': 'నికర బంగారు బరువు',
      'gross_weight': 'మొత్తం బరువు',
      'purity': 'బంగారు స్వచ్ఛత',
      'valuation': 'మార్కెట్ విలువ',
      'view_certificate': 'సర్టిఫికేట్ చూడండి',
      'download_pdf': 'PDF డౌన్‌లోడ్ చేయండి',
      'print': 'ప్రింట్ చేయండి',
      'pay_interest': 'వడ్డీ చెల్లించండి',
      'customer_portal': 'కస్టమర్ పోర్టల్',
      'owner_login': 'ఓనర్ లాగిన్',
      'customer_login': 'కస్టమర్ OTP లాగిన్',
      'mobile_number': 'మొబైల్ నంబర్',
      'verify_and_continue': 'ధృవీకరించి కొనసాగించండి',
      'language': 'భాష',
      'select_language': 'యాప్ భాషను ఎంచుకోండి',
      'status': 'స్థితి',
      'active': 'క్రియాశీలం',
      'closed': 'ముగిసింది',
      'vault_secure': 'వాల్ట్ సురక్షితం',
      'core_operations': 'ప్రధాన కార్యకలాపాలు',
      'jewellery_and_assets': 'ఆభరణాలు & ఆస్తులు',
      'finance_and_analytics': 'ఆర్థిక & విశ్లేషణలు',
      'security_and_audit': 'భద్రత & ఆడిట్',
      'store_administration': 'స్టోర్ నిర్వహణ',
      'accounting_ledger': 'ఖాతా పుస్తకం (లెడ్జర్)',
      'reports_and_analytics': 'నివేదికలు & విశ్లేషణలు',
      'audit_log': 'ఆడిట్ లాగ్',
      'security_activity': 'భద్రతా కార్యకలాపాలు',
      'notifications': 'నోటిఫికేషన్లు',
      'owner_profile': 'ఓనర్ ప్రొఫైల్',
      'store_settings': 'స్టోర్ సెట్టింగ్‌లు',
      'help_and_docs': 'సహాయం & డాక్యుమెంట్స్',
      'kyc_verification': 'KYC తనిఖీ',
      'inventory_and_stock': 'ఆభరణాలు & స్టాక్',
      'pledges_and_loans': 'తాకట్టు & రుణాలు',
      'welcome_back': 'తిరిగి స్వాగతం',
      'active_loans': 'క్రియాశీల రుణాలు',
      'total_due_amount': 'మొత్తం బకాయి',
      'search_placeholder': 'కస్టమర్లు, రుణాలు శోధించండి...',
      'select_branch': 'బ్రాంచ్‌ను ఎంచుకోండి',
      'view_all': 'అన్నీ చూడండి',
      'language_and_regional': 'భాష & ప్రాంతీయ ప్రాధాన్యతలు',
      'select_app_language_desc': 'కారట్‌కోర్ ERP కోసం మీకు నచ్చిన భాషను ఎంచుకోండి',
      // Loans & Reports In-Page Strings
      'new_loan_and_pledge': 'కొత్త రుణం & తాకట్టు',
      'loan_reports': 'రుణ నివేదికలు',
      'outstanding_principal': 'బకాయి అసలు',
      'interest_accrued_due': 'చెల్లించాల్సిన వడ్డీ',
      'total_collateral_value': 'మొత్తం కొలేటరల్ విలువ',
      'loan_portfolio_analytics': 'రుణ పోర్ట్‌ఫోలియో & కొలేటరల్ విశ్లేషణలు',
      'collateral_distribution': 'కొలేటరల్ పంపిణీ',
      'gold_collateral_loans': 'బంగారు కొలేటరల్ రుణాలు',
      'silver_collateral_loans': 'వెండి కొలేటరల్ రుణాలు',
      'loan_health_performance': 'రుణ ఆరోగ్య పనితీరు',
      'current_on_time_loans': 'సమయానికి చెల్లించే రుణాలు',
      'overdue_interest_accounts': 'బకాయి వడ్డీ ఖాతాలు',
      'search_loans_placeholder': 'రుణ ఐడి, కస్టమర్ పేరు, మొబైల్ ద్వారా శోధించండి...',
      'filters': 'ఫిల్టర్లు',
      'date_disbursed_newest': 'పంపిణీ చేసిన తేదీ (కొత్తది)',
      'enterprise_module': 'ఎంటర్‌ప్రైజ్ మాడ్యూల్',
      'pledge_and_loans_desc': 'సురక్షిత లోహ రుణాలు, తాకట్టు నిల్వలు, వడ్డీ లెక్కలు మరియు చెల్లింపుల పరిష్కారం.',
      'reports_and_bi_center': 'నివేదికలు & బిజినెస్ ఇంటెలిజెన్స్ కేంద్రం',
      'reports_bi_desc': 'ఎగ్జిక్యూటివ్ డాష్‌బోర్డులు, కార్యాచరణ విశ్లేషణలు మరియు ఆర్థిక నివేదికలు',
      'report_date_filter': 'నివేదిక తేదీ ఫిల్టర్',
      'comparison_mode': 'పోలిక మోడ్',
      'no_comparison': 'పోలిక లేదు',
      'today': 'ఈరోజు',
      'yesterday': 'నిన్న',
      'this_week': 'ఈ వారం',
      'this_month': 'ఈ నెల',
      'last_month': 'గత నెల',
      'this_quarter': 'ఈ త్రైమాసికం',
      'this_year': 'ఈ సంవత్సరం',
      'financial_year': 'ఆర్థిక సంవత్సరం',
      'custom_range': 'కస్టమ్ పరిధి',
      'attention_required': 'శ్రద్ధ అవసరం — యాక్షన్ ప్యానెల్',
      'attention_required_desc': 'ఓనర్/మేనేజర్ చర్య అవసరమైన ఆపరేషనల్ సూచికలు',
      'executive_kpi_metrics': 'ఎగ్జిక్యూటివ్ KPI సారాంశం',
      'revenue': 'ఆదాయం',
      'expenses': 'ఖర్చులు',
      'net_profit': 'నికర లాభం',
      'loan_outstanding': 'బకాయి రుణం',
      'interest_income': 'వడ్డీ ఆదాయం',
      'inventory_value': 'స్టాక్ విలువ',
      'pledged_inventory': 'తాకట్టు పెట్టిన స్టాక్',
      'customer_count': 'కస్టమర్ల సంఖ్య',
      'overdue_loans': 'గడువు ముగిసిన రుణాలు',
      'cash_balance': 'నగదు నిల్వ',
      'overdue_gold_loans': 'గడువు ముగిసిన బంగారు రుణాలు',
      'pending_kyc_records': 'పెండింగ్‌లో ఉన్న KYC రికార్డులు',
      'loans_awaiting_approval': 'ఆమోదం కోసం వేచి ఉన్న రుణాలు',
      'ornaments_requiring_attention': 'శ్రద్ధ అవసరమైన ఆభరణాలు',
      'overdue_receivables': 'బకాయి రాబడులు',
      'high_risk_customers': 'అధిక రిస్క్ ఉన్న కస్టమర్ రికార్డులు',
      'bank_balance': 'బ్యాంక్ నిల్వ',
      'saved_pinned_reports': 'సేవ్ చేసిన మరియు పిన్ చేసిన నివేదిక వీక్షణలు',
      'recent_reports': 'ఇటీవలి నివేదికలు మరియు ఇష్టమైనవి',
      'dedicated_reports_directory': 'ప్రత్యేక నివేదిక మాడ్యూల్స్ డైరెక్టరీ',
      'reset_filters': 'ఫిల్టర్‌లను రీసెట్ చేయండి',
      'previous_period': 'మునుపటి కాలం',
      'same_period_last_year': 'గత సంవత్సరం ఇదే కాలం',
    },
    'kn': {
      'app_name': 'ಕ್ಯಾರಟ್‌ಕೋರ್ ERP',
      'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'customers': 'ಗ್ರಾಹಕರು',
      'ornaments': 'ಆಭರಣಗಳು ಮತ್ತು ದಾಸ್ತಾನು',
      'my_pledged_ornaments': 'ನನ್ನ ಅಡಮಾನ ಆಭರಣಗಳು',
      'quality_certificates': 'ಗುಣಮಟ್ಟ ಪ್ರಮಾಣಪತ್ರಗಳು',
      'loans': 'ಅಡಮಾನ ಮತ್ತು ಸಾಲಗಳು',
      'my_loans': 'ನನ್ನ ಸಕ್ರಿಯ ಸಾಲಗಳು',
      'payments': 'ಪಾವತಿಗಳು ಮತ್ತು ರಸೀದಿಗಳು',
      'profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
      'kyc': 'ಕೆವೈಸಿ ಪರಿಶೀಲನೆ',
      'settings': 'ಅಂಗಡಿ ಸಂಯೋಜನೆಗಳು',
      'security': 'ಸುರಕ್ಷತೆ ಮತ್ತು 2FA',
      'otp_verification': 'OTP ಭದ್ರತಾ ಪರಿಶೀಲನೆ',
      'enter_otp': '6-ಅಂಕಿಯ OTP ನಮೂದಿಸಿ',
      'send_otp': 'OTP ಕಳುಹಿಸಿ',
      'resend_otp': 'OTP ಮರುಕಳುಹಿಸಿ',
      'two_factor_auth': 'ದ್ವಿ-ಅಂಶ ದೃಢೀಕರಣ (2FA)',
      'enable_2fa': '2FA ಸುರಕ್ಷತೆ ಸಕ್ರಿಯಗೊಳಿಸಿ',
      'disable_2fa': '2FA ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ',
      'authenticator_app': 'ಅಥೆಂಟಿಕೇಟರ್ ಆಪ್ (TOTP)',
      'safe_vault_storage': 'ಸುರಕ್ಷಿತ ವಾಲ್ಟ್ ಸಂಗ್ರಹಣೆ',
      'bis_hallmark': 'BIS ಹಾಲ್‌ಮಾರ್ಕ್ 916 ಪ್ರಮಾಣೀಕೃತ',
      'net_weight': 'ನಿವ್ವಳ ಚಿನ್ನದ ತೂಕ',
      'gross_weight': 'ಒಟ್ಟು ತೂಕ',
      'purity': 'ಚಿನ್ನದ ಶುದ್ಧತೆ',
      'valuation': 'ಮೌಲ್ಯಮಾಪನ ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
      'view_certificate': 'ಗುಣಮಟ್ಟ ಪ್ರಮಾಣಪತ್ರ ವೀಕ್ಷಿಸಿ',
      'download_pdf': 'ಪ್ರಮಾಣಪತ್ರ PDF ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
      'print': 'ಮುದ್ರಿಸಿ',
      'pay_interest': 'ಬಡ್ಡಿ ಪಾವತಿಸಿ',
      'customer_portal': 'ಗ್ರಾಹಕ ಪೋರ್ಟಲ್',
      'owner_login': 'ಮಾಲೀಕರ ಲಾಗಿನ್',
      'customer_login': 'ಗ್ರಾಹಕ OTP ಲಾಗಿನ್',
      'mobile_number': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'verify_and_continue': 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ',
      'language': 'ಭಾಷೆ',
      'select_language': 'ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
      'status': 'ಸ್ಥಿತಿ',
      'active': 'ಸಕ್ರಿಯ',
      'closed': 'ಮುಕ್ತಾಯಗೊಂಡಿದೆ',
      'vault_secure': 'ವಾಲ್ಟ್ ಸುರಕ್ಷಿತ',
      'core_operations': 'ಮುಖ್ಯ ಕಾರ್ಯಾಚರಣೆಗಳು',
      'jewellery_and_assets': 'ಆಭರಣಗಳು & ಆಸ್ತಿಗಳು',
      'finance_and_analytics': 'ಹಣಕಾಸು & ವಿಶ್ಲೇಷಣೆ',
      'security_and_audit': 'ಭದ್ರತೆ & ಆಡಿಟ್',
      'store_administration': 'ಅಂಗಡಿ ಆಡಳಿತ',
      'accounting_ledger': 'ಖಾತೆ ಲೆಡ್ಜರ್',
      'reports_and_analytics': 'ವರದಿಗಳು & ವಿಶ್ಲೇಷಣೆ',
      'audit_log': 'ಆಡಿಟ್ ಲಾಗ್',
      'security_activity': 'ಭದ್ರತಾ ಚಟುವಟಿಕೆ',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'owner_profile': 'ಮಾಲೀಕರ ವಿವರ',
      'store_settings': 'ಅಂಗಡಿ ಸಂಯೋಜನೆಗಳು',
      'help_and_docs': 'ಸಹಾಯ & ದಾಖಲೆಗಳು',
      'kyc_verification': 'ಕೆವೈಸಿ ಪರಿಶೀಲನೆ',
      'inventory_and_stock': 'ಆಭರಣಗಳು ಮತ್ತು ದಾಸ್ತಾನು',
      'pledges_and_loans': 'ಅಡಮಾನ ಮತ್ತು ಸಾಲಗಳು',
      'welcome_back': 'ಮರಳಿ ಸ್ವಾಗತ',
      'active_loans': 'ಸಕ್ರಿಯ ಸಾಲಗಳು',
      'total_due_amount': 'ಒಟ್ಟು ಬಾಕಿ ಮೊತ್ತ',
      'search_placeholder': 'ಗ್ರಾಹಕರು, ಸಾಲಗಳನ್ನು ಹುಡುಕಿ...',
      'select_branch': 'ಶಾಖೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'view_all': 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
      'language_and_regional': 'ಭಾಷೆ ಮತ್ತು ಪ್ರಾದೇಶಿಕ ಆದ್ಯತೆಗಳು',
      'select_app_language_desc': 'ಕ್ಯಾರಟ್‌ಕೋರ್ ERP ಗಾಗಿ ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      // Loans & Reports In-Page Strings
      'new_loan_and_pledge': 'ಹೊಸ ಸಾಲ ಮತ್ತು ಅಡಮಾನ',
      'loan_reports': 'ಸಾಲ ವರದಿಗಳು',
      'outstanding_principal': 'ಬಾಕಿ ಅಸಲು',
      'interest_accrued_due': 'ಗಳಿಸಿದ ಬಡ್ಡಿ ಬಾಕಿ',
      'total_collateral_value': 'ಒಟ್ಟು ಭದ್ರತಾ ಮೌಲ್ಯ',
      'loan_portfolio_analytics': 'ಸಾಲ ಪೋರ್ಟ್‌ಫೋಲಿಯೊ ಮತ್ತು ಭದ್ರತಾ ವಿಶ್ಲೇಷಣೆ',
      'collateral_distribution': 'ಭದ್ರತಾ ವಿತರಣೆ',
      'gold_collateral_loans': 'ಚಿನ್ನದ ಭದ್ರತಾ ಸಾಲಗಳು',
      'silver_collateral_loans': 'ಬೆಳ್ಳಿ ಭದ್ರತಾ ಸಾಲಗಳು',
      'loan_health_performance': 'ಸಾಲದ ಆರೋಗ್ಯ ನಿರ್ವಹಣೆ',
      'current_on_time_loans': 'ಸಮಯಕ್ಕೆ ಸರಿಯಾದ ಸಾಲಗಳು',
      'overdue_interest_accounts': 'ಬಾಕಿ ಬಡ್ಡಿ ಖಾತೆಗಳು',
      'search_loans_placeholder': 'ಸಾಲ ಐಡಿ, ಗ್ರಾಹಕರ ಹೆಸರು, ಮೊಬೈಲ್ ಮೂಲಕ ಹುಡುಕಿ...',
      'filters': 'ಫಿಲ್ಟರ್‌ಗಳು',
      'date_disbursed_newest': 'ವಿತರಣೆಯ ದಿನಾಂಕ (ಹೊಸದು)',
      'enterprise_module': 'ಎಂಟರ್‌ಪ್ರೈಸ್ ಮಾಡ್ಯೂಲ್',
      'pledge_and_loans_desc': 'ಸುರಕ್ಷಿತ ಅಮೂಲ್ಯ ಲೋಹದ ಸಾಲಗಳು, ಗ್ರಾಹಕರ ಅಡಮಾನಗಳು, ಬಡ್ಡಿ ಲೆಕ್ಕಾಚಾರ ಮತ್ತು ಇತ್ಯರ್ಥ.',
      'reports_and_bi_center': 'ವರದಿಗಳು ಮತ್ತು ವ್ಯಾಪಾರ ಗುಪ್ತಚರ ಕೇಂದ್ರ',
      'reports_bi_desc': 'ಕಾರ್ಯನಿರ್ವಾಹಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗಳು, ಕಾರ್ಯಾಚರಣೆಯ ವಿಶ್ಲೇಷಣೆಗಳು ಮತ್ತು ಹಣಕಾಸು ವರದಿಗಳು',
      'report_date_filter': 'ವರದಿ ದಿನಾಂಕ ಫಿಲ್ಟರ್',
      'comparison_mode': 'ಹೋಲಿಕೆ ಮೋಡ್',
      'no_comparison': 'ಯಾವುದೇ ಹೋಲಿಕೆ ಇಲ್ಲ',
      'today': 'ಇಂದು',
      'yesterday': 'ನಿನ್ನೆ',
      'this_week': 'ಈ ವಾರ',
      'this_month': 'ಈ ತಿಂಗಳು',
      'last_month': 'ಕಳೆದ ತಿಂಗಳು',
      'this_quarter': 'ಈ ತ್ರೈಮಾಸಿಕ',
      'this_year': 'ಈ ವರ್ಷ',
      'financial_year': 'ಹಣಕಾಸು ವರ್ಷ',
      'custom_range': 'ಕಸ್ಟಮ್ ಶ್ರೇಣಿ',
      'attention_required': 'ಗಮನ ಅಗತ್ಯವಿದೆ — ಕ್ರಿಯಾ ಫಲಕ',
      'attention_required_desc': 'ಮಾಲೀಕರು/ವ್ಯವಸ್ಥಾಪಕರ ಕ್ರಮ ಅಗತ್ಯವಿರುವ ಕಾರ್ಯಾಚರಣೆಯ ಸೂಚಕಗಳು',
      'executive_kpi_metrics': 'ಕಾರ್ಯನಿರ್ವಾಹಕ ಕೆಪಿಐ ಸಾರಾಂಶ',
      'revenue': 'ಆದಾಯ',
      'expenses': 'ವೆಚ್ಚಗಳು',
      'net_profit': 'ನಿವ್ವಳ ಲಾಭ',
      'loan_outstanding': 'ಸಾಲದ ಬಾಕಿ',
      'interest_income': 'ಬಡ್ಡಿ ಆದಾಯ',
      'inventory_value': 'ದಾಸ್ತಾನು ಮೌಲ್ಯ',
      'pledged_inventory': 'ಅಡಮಾನವಿಟ್ಟ ದಾಸ್ತಾನು',
      'customer_count': 'ಗ್ರಾಹಕರ ಸಂಖ್ಯೆ',
      'overdue_loans': 'ಅವಧಿ ಮೀರಿದ ಸಾಲಗಳು',
      'cash_balance': 'ನಗದು ಬಾಕಿ',
      'overdue_gold_loans': 'ಅವಧಿ ಮೀರಿದ ಚಿನ್ನದ ಸಾಲಗಳು',
      'pending_kyc_records': 'ಬಾಕಿ ಇರುವ KYC ದಾಖಲೆಗಳು',
      'loans_awaiting_approval': 'ಅನುಮೋದನೆಗಾಗಿ ಕಾಯುತ್ತಿರುವ ಸಾಲಗಳು',
      'ornaments_requiring_attention': 'ಗಮನ ಅಗತ್ಯವಿರುವ ಆಭರಣಗಳು',
      'overdue_receivables': 'ಅವಧಿ ಮೀರಿದ ಬರಬೇಕಾದ ಬಾಕಿ',
      'high_risk_customers': 'ಹೆಚ್ಚಿನ ಅಪಾಯದ ಗ್ರಾಹಕರ ದಾಖಲೆಗಳು',
      'bank_balance': 'ಬ್ಯಾಂಕ್ ಬ್ಯಾಲೆನ್ಸ್',
      'saved_pinned_reports': 'ಉಳಿಸಿದ ಮತ್ತು ಪಿನ್ ಮಾಡಿದ ವರದಿ ವೀಕ್ಷಣೆಗಳು',
      'recent_reports': 'ಇತ್ತೀಚಿನ ವರದಿಗಳು ಮತ್ತು ಮೆಚ್ಚಿನವುಗಳು',
      'dedicated_reports_directory': 'ಮೀಸಲಾದ ವರದಿ ಮಾಡ್ಯೂಲ್‌ಗಳ ಡೈರೆಕ್ಟರಿ',
      'reset_filters': 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಮರುಹೊಂದಿಸಿ',
      'previous_period': 'ಹಿಂದಿನ ಅವಧಿ',
      'same_period_last_year': 'ಕಳೆದ ವರ್ಷದ ಇದೇ ಅವಧಿ',
    },
    'gu': {
      'app_name': 'કેરેટકોર ERP',
      'dashboard': 'ડેશબોર્ડ',
      'customers': 'ગ્રાહકો',
      'ornaments': 'દાગીના અને સ્ટોક',
      'my_pledged_ornaments': 'મારા ગીરવે મૂકેલા દાગીના',
      'quality_certificates': 'ગુણવત્તા પ્રમાણપત્રો',
      'loans': 'ધીરાણ અને લોન',
      'my_loans': 'મારી સક્રિય લોન',
      'payments': 'ચૂકવણી અને રસીદો',
      'profile': 'મારી પ્રોફાઇલ',
      'kyc': 'KYC ચકાસણી',
      'settings': 'સ્ટોર સેટિંગ્સ',
      'security': 'સુરક્ષા અને 2FA',
      'otp_verification': 'OTP સુરક્ષા ચકાસણી',
      'enter_otp': '6-આંકડાનો OTP દાખલ કરો',
      'send_otp': 'OTP મોકલો',
      'resend_otp': 'ફરીથી OTP મોકલો',
      'two_factor_auth': 'ટુ-ફેક્ટર ઓથેન્ટિકેશન (2FA)',
      'enable_2fa': '2FA સુરક્ષા સક્ષમ કરો',
      'disable_2fa': '2FA અક્ષમ કરો',
      'authenticator_app': 'ઓથેન્ટિકેટર એપ (TOTP)',
      'safe_vault_storage': 'સુરક્ષિત તિજોરી',
      'bis_hallmark': 'BIS હોલમાર્ક 916 પ્રમાણિત',
      'net_weight': 'શુદ્ધ સોનાનું વજન',
      'gross_weight': 'કુલ વજન',
      'purity': 'સોનાની શુદ્ધતા',
      'valuation': 'બજાર મૂલ્યાંકન',
      'view_certificate': 'પ્રમાણપત્ર જુઓ',
      'download_pdf': 'PDF ડાઉનલોડ કરો',
      'print': 'પ્રિન્ટ કરો',
      'pay_interest': 'વ્યાજ ચૂકવો',
      'customer_portal': 'ગ્રાહક પોર્ટલ',
      'owner_login': 'ઓનર લોગિન',
      'customer_login': 'ગ્રાહક OTP લોગિન',
      'mobile_number': 'મોબાઈલ નંબર',
      'verify_and_continue': 'ચકાસો અને આગળ વધો',
      'language': 'ભાષા',
      'select_language': 'એપ ભાષા પસંદ કરો',
      'status': 'સ્થિતિ',
      'active': 'સક્રિય',
      'closed': 'બંધ',
      'vault_secure': 'તિજોરી સુરક્ષિત',
      'core_operations': 'મુખ્ય કામગીરી',
      'jewellery_and_assets': 'દાગીના અને અસ્કયામતો',
      'finance_and_analytics': 'નાણાં અને વિશ્લેષણ',
      'security_and_audit': 'સુરક્ષા અને ઓડિટ',
      'store_administration': 'સ્ટોર વહીવટ',
      'accounting_ledger': 'નામા વહી (ખાતાવહી)',
      'reports_and_analytics': 'અહેવાલો અને વિશ્લેષણ',
      'audit_log': 'ઓડિટ લોગ',
      'security_activity': 'સુરક્ષા પ્રવૃત્તિ',
      'notifications': 'સૂચનાઓ અને ચેતવણીઓ',
      'owner_profile': 'માલિક પ્રોફાઇલ',
      'store_settings': 'સ્ટોર સેટિંગ્સ',
      'help_and_docs': 'મદદ અને દસ્તાવેજો',
      'kyc_verification': 'KYC ચકાસણી',
      'inventory_and_stock': 'દાગીના અને સ્ટોક',
      'pledges_and_loans': 'ધીરાણ અને લોન',
      'welcome_back': 'પાછા સ્વાગત છે',
      'active_loans': 'સક્રિય લોન',
      'total_due_amount': 'કુલ બાકી રકમ',
      'search_placeholder': 'ગ્રાહકો, લોન શોધો...',
      'select_branch': 'શાખા પસંદ કરો',
      'view_all': 'બધું જુઓ',
      'language_and_regional': 'ભાષા અને પ્રાદેશિક પસંદગીઓ',
      'select_app_language_desc': 'કેરેટકોર ERP સિસ્ટમ માટે તમારી પસંદગીની ભાષા પસંદ કરો',
      // Loans & Reports In-Page Strings
      'new_loan_and_pledge': 'નવી લોન અને ગીરવે',
      'loan_reports': 'લોન અહેવાલો',
      'outstanding_principal': 'બાકી મુદલ',
      'interest_accrued_due': 'ઉપાર્જિત વ્યાજ',
      'total_collateral_value': 'કુલ ગીરવે મૂલ્ય',
      'loan_portfolio_analytics': 'લોન પોર્ટફોલિયો અને ગીરવે વિશ્લેષણ',
      'collateral_distribution': 'ગીરવે વિતરણ',
      'gold_collateral_loans': 'સોના ગીરવે લોન',
      'silver_collateral_loans': 'ચાંદી ગીરવે લોન',
      'loan_health_performance': 'લોન પ્રદર્શન',
      'current_on_time_loans': 'સમયસર ચાલતી લોન',
      'overdue_interest_accounts': 'બાકી વ્યાજ ખાતાઓ',
      'search_loans_placeholder': 'લોન આઈડી, ગ્રાહક નામ દ્વારા શોધો...',
      'filters': 'ફિલ્ટર્સ',
      'date_disbursed_newest': 'ચૂકવણી તારીખ (નવીનતમ)',
      'enterprise_module': 'એન્ટરપ્રાઇઝ મોડ્યુલ',
      'pledge_and_loans_desc': 'કિંમતી ધાતુ ધિરાણ, ગ્રાહક ગીરવે, વ્યાજની ગણતરી અને પતાવટ.',
      'reports_and_bi_center': 'અહેવાલો અને બિઝનેસ ઇન્ટેલિજન્સ સેન્ટર',
      'reports_bi_desc': 'એક્ઝિક્યુટિવ ડેશબોર્ડ, ઓપરેશનલ એનાલિટિક્સ અને નાણાકીય નિવેદનો',
      'report_date_filter': 'અહેવાલ તારીખ ફિલ્ટર',
      'comparison_mode': 'સરખામણી મોડ',
      'no_comparison': 'કોઈ સરખામણી નથી',
      'today': 'આજે',
      'yesterday': 'ગઈકાલે',
      'this_week': 'આ અઠવાડિયે',
      'this_month': 'આ મહિને',
      'last_month': 'ગયા મહિને',
      'this_quarter': 'આ ક્વાર્ટર',
      'this_year': 'આ વર્ષે',
      'financial_year': 'નાણાકીય વર્ષ',
      'custom_range': 'કસ્ટમ શ્રેણી',
      'attention_required': 'ધ્યાન આપવું જરૂરી — એક્શન પેનલ',
      'attention_required_desc': 'ઓનર/મેનેજરની કાર્યવાહી જરૂરી હોય તેવા ઓપરેશનલ સૂચકાંકો',
      'executive_kpi_metrics': 'એક્ઝિક્યુટિવ KPI સારાંશ',
      'revenue': 'આવક',
      'expenses': 'ખર્ચ',
      'net_profit': 'ચોખ્ખો નફો',
      'loan_outstanding': 'બાકી લોન',
      'interest_income': 'વ્યાજ આવક',
      'inventory_value': 'સ્ટોક મૂલ્ય',
      'pledged_inventory': 'ગીરવે સ્ટોક',
      'customer_count': 'ગ્રાહકોની સંખ્યા',
      'overdue_loans': 'મુદતવીતી લોન',
      'cash_balance': 'રોકડ સિલક',
      'overdue_gold_loans': 'મુદતવીતી સોનાની લોન',
      'pending_kyc_records': 'બાકી KYC રેકોર્ડ્સ',
      'loans_awaiting_approval': 'મંજૂરી માટે બાકી લોન',
      'ornaments_requiring_attention': 'ધ્યાન જરૂરી હોય તેવા દાગીના',
      'overdue_receivables': 'બાકી લેણાં',
      'high_risk_customers': 'ઉચ્ચ જોખમી ગ્રાહક રેકોર્ડ્સ',
      'bank_balance': 'બેંક સિલક',
      'saved_pinned_reports': 'સાચવેલા અને પિન કરેલા રિપોર્ટ વ્યુ',
      'recent_reports': 'તાજેતરના રિપોર્ટ્સ અને મનપસંદ',
      'dedicated_reports_directory': 'સમર્પિત રિપોર્ટ મોડ્યુલ્સ ડિરેક્ટરી',
      'reset_filters': 'ફિલ્ટર્સ રીસેટ કરો',
      'previous_period': 'અગાઉનો સમયગાળો',
      'same_period_last_year': 'ગયા વર્ષનો સમાન સમયગાળો',
    },
    'mr': {
      'app_name': 'कॅरेटकोर ERP',
      'dashboard': 'डॅशबोर्ड',
      'customers': 'ग्राहक',
      'ornaments': 'दागिने आणि साठा',
      'my_pledged_ornaments': 'माझे गहाण ठेवलेले दागिने',
      'quality_certificates': 'गुणवत्ता प्रमाणपत्रे',
      'loans': 'गहाण आणि कर्जे',
      'my_loans': 'माझी सक्रिय कर्जे',
      'payments': 'पेमेंट्स आणि पावत्या',
      'profile': 'माझी प्रोफाइल',
      'kyc': 'केवायसी पडताळणी',
      'settings': 'स्टोअर सेटिंग्ज',
      'security': 'सुरक्षा आणि 2FA',
      'otp_verification': 'OTP सुरक्षा पडताळणी',
      'enter_otp': '6-अंकी OTP प्रविष्ट करा',
      'send_otp': 'OTP पाठवा',
      'resend_otp': 'पुन्हा OTP पाठवा',
      'two_factor_auth': 'टू-फॅक्टर ऑथेंटिकेशन (2FA)',
      'enable_2fa': '2FA सुरक्षा सक्षम करा',
      'disable_2fa': '2FA अक्षम करा',
      'authenticator_app': 'ऑथेंटिकेटर अ‍ॅप (TOTP)',
      'safe_vault_storage': 'सुरक्षित व्हॉल्ट स्टोरेज',
      'bis_hallmark': 'BIS हॉलमार्क 916 प्रमाणित',
      'net_weight': 'शुद्ध सोन्याचे वजन',
      'gross_weight': 'एकूण वजन',
      'purity': 'सोन्याची शुद्धता',
      'valuation': 'मूल्यांकन बाजार किंमत',
      'view_certificate': 'प्रमाणपत्र पहा',
      'download_pdf': 'प्रमाणपत्र PDF डाउनलोड करा',
      'print': 'प्रिंट करा',
      'pay_interest': 'व्याज भरा',
      'customer_portal': 'ग्राहक पोर्टल',
      'owner_login': 'मालक लॉगिन',
      'customer_login': 'ग्राहक OTP लॉगिन',
      'mobile_number': 'मोबाईल नंबर',
      'verify_and_continue': 'पडताळणी करा आणि पुढे जा',
      'language': 'भाषा',
      'select_language': 'अ‍ॅप भाषा निवडा',
      'status': 'स्थिती',
      'active': 'सक्रिय',
      'closed': 'बंद',
      'vault_secure': 'व्हॉल्ट सुरक्षित',
      'core_operations': 'मुख्य ऑपरेशन्स',
      'jewellery_and_assets': 'दागिने आणि मालमत्ता',
      'finance_and_analytics': 'वित्त आणि विश्लेषण',
      'security_and_audit': 'सुरक्षा आणि ऑडिट',
      'store_administration': 'स्टोअर प्रशासन',
      'accounting_ledger': 'खातावही (खतावणी)',
      'reports_and_analytics': 'अहवाल आणि विश्लेषण',
      'audit_log': 'ऑडिट लॉग',
      'security_activity': 'सुरक्षा हालचाली',
      'notifications': 'सूचना आणि सूचना फलक',
      'owner_profile': 'मालक प्रोफाइल',
      'store_settings': 'स्टोअर सेटिंग्ज',
      'help_and_docs': 'मदत आणि दस्तऐवज',
      'kyc_verification': 'केवायसी पडताळणी',
      'inventory_and_stock': 'दागिने आणि साठा',
      'pledges_and_loans': 'गहाण आणि कर्जे',
      'welcome_back': 'पुन्हा स्वागत आहे',
      'active_loans': 'सक्रिय कर्जे',
      'total_due_amount': 'एकूण देय रक्कम',
      'search_placeholder': 'ग्राहक, कर्जे शोधा...',
      'select_branch': 'शाखा निवडा',
      'view_all': 'सर्व पहा',
      'language_and_regional': 'भाषा आणि प्रादेशिक प्राधान्ये',
      'select_app_language_desc': 'कॅरेटकोर ERP प्रणालीसाठी तुमची पसंतीची भाषा निवडा',
      // Loans & Reports In-Page Strings
      'new_loan_and_pledge': 'नवीन कर्ज आणि गहाण',
      'loan_reports': 'कर्ज अहवाल',
      'outstanding_principal': 'थकीत मुद्दल',
      'interest_accrued_due': 'जमा झालेले व्याज',
      'total_collateral_value': 'एकूण तारण मूल्य',
      'loan_portfolio_analytics': 'कर्ज पोर्टफोलिओ आणि तारण विश्लेषण',
      'collateral_distribution': 'तारण वाटप',
      'gold_collateral_loans': 'सुवर्ण तारण कर्जे',
      'silver_collateral_loans': 'चांदी तारण कर्जे',
      'loan_health_performance': 'कर्ज कामगिरी',
      'current_on_time_loans': 'वेळेवर असणारी कर्जे',
      'overdue_interest_accounts': 'थकीत व्याज खाती',
      'search_loans_placeholder': 'कर्ज आयडी, ग्राहक नाव द्वारे शोधा...',
      'filters': 'फिल्टर्स',
      'date_disbursed_newest': 'वितरण तारीख (नवीनतम)',
      'enterprise_module': 'एंटरप्राइझ मॉड्यूल',
      'pledge_and_loans_desc': 'सुरक्षित धातू कर्जे, ग्राहक गहाण, व्याज आकारणी आणि सेटलमेंट.',
      'reports_and_bi_center': 'अहवाल आणि व्यवसाय विश्लेषण केंद्र',
      'reports_bi_desc': 'कार्यकारी डॅशबोर्ड, ऑपरेशनल विश्लेषण आणि आर्थिक विवरणपत्रे',
      'report_date_filter': 'अहवाल तारीख फिल्टर',
      'comparison_mode': 'तुलना मोड',
      'no_comparison': 'तुलना नाही',
      'today': 'आज',
      'yesterday': 'काल',
      'this_week': 'या आठवड्यात',
      'this_month': 'या महिन्यात',
      'last_month': 'मागील महिन्यात',
      'this_quarter': 'या तिमाहीत',
      'this_year': 'या वर्षी',
      'financial_year': 'आर्थिक वर्ष',
      'custom_range': 'सानुकूल श्रेणी',
      'attention_required': 'लक्ष देणे आवश्यक — कृती पॅनेल',
      'attention_required_desc': 'मालक/व्यवस्थापक कारवाई आवश्यक असणारे ऑपरेशनल निर्देशक',
      'executive_kpi_metrics': 'कार्यकारी KPI सारांश',
      'revenue': 'महसूल',
      'expenses': 'खर्च',
      'net_profit': 'निव्वळ नफा',
      'loan_outstanding': 'थकीत कर्ज',
      'interest_income': 'व्याज उत्पन्न',
      'inventory_value': 'साठा मूल्य',
      'pledged_inventory': 'गहाण ठेवलेला साठा',
      'customer_count': 'ग्राहक संख्या',
      'overdue_loans': 'थकीत कर्जे',
      'cash_balance': 'रोख शिल्लक',
      'overdue_gold_loans': 'थकीत सुवर्ण कर्जे',
      'pending_kyc_records': 'प्रलंबित KYC नोंदी',
      'loans_awaiting_approval': 'मंजुरी प्रलंबित कर्जे',
      'ornaments_requiring_attention': 'लक्ष देण्याची आवश्यकता असलेले दागिने',
      'overdue_receivables': 'थकीत येणी',
      'high_risk_customers': 'उच्च-जोखीम ग्राहक नोंदी',
      'bank_balance': 'बँक शिल्लक',
      'saved_pinned_reports': 'जतन केलेले आणि पिन केलेले अहवाल दृश्य',
      'recent_reports': 'अलीकडील अहवाल आणि आवडी',
      'dedicated_reports_directory': 'समर्पित अहवाल विभाग निर्देशिका',
      'reset_filters': 'फिल्टर रीसेट करा',
      'previous_period': 'मागील कालावधी',
      'same_period_last_year': 'गेल्या वर्षीचा समान कालावधी',
    },
  };

  String translate(String key) {
    final languageCode = locale.languageCode;
    return _localizedValues[languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  static const Set<String> supportedLanguageCodes = {
    'en', 'hi', 'ta', 'te', 'kn', 'gu', 'mr',
  };

  @override
  bool isSupported(Locale locale) {
    return supportedLanguageCodes.contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

extension LocalizationContextExtension on BuildContext {
  String tr(String key) {
    return AppLocalizations.of(this).translate(key);
  }
}
